import { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    absolute: "",
    default: "Next Js Tutorial.",
    template: "%s | Dinoevolution",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header>
          <div>Header</div>
        </header>
        {children}
        <footer>
          <div>Footer</div>
        </footer>
      </body>
    </html>
  );
}
